# Generated by Django 5.0.8 on 2025-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeRequest',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('printer_no', models.CharField(max_length=200)),
                ('employee_no', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('usage_status', models.CharField(max_length=100)),
                ('hod_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('hod_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cartridge_request',
            },
        ),
    ]
