# Generated by Django 5.0.8 on 2025-07-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridgerequest',
            name='usage_status',
            field=models.CharField(choices=[('Self', 'Self'), ('Common Employee', 'Common Employee')], max_length=100),
        ),
    ]
