# Generated by Django 5.0.8 on 2025-07-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Permission', '0002_alter_cartridgerequest_usage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
            ],
        ),
    ]
