# Generated by Django 5.0.8 on 2025-07-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Permission', '0003_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
