# Generated by Django 5.0.8 on 2025-07-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Permission', '0004_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MISAsset',
            fields=[
                ('printer_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emp_no', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('usage_status', models.CharField(choices=[('Self', 'Self'), ('Common Employee', 'Common Employee')], max_length=100)),
            ],
            options={
                'db_table': 'MISAsset',
            },
        ),
    ]
