# Generated by Django 5.0.8 on 2025-07-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PC_Permission', '0005_misasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridgerequest',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
    ]
